# Generated by Django 2.2.5 on 2019-11-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('ColorTag', models.CharField(max_length=50)),
                ('Brand', models.CharField(max_length=50)),
            ],
        ),
    ]
