# Generated by Django 2.2.5 on 2019-12-10 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('raiment', '0001_initial'), ('raiment', '0002_auto_20191105_1802'), ('raiment', '0003_auto_20191105_1802'), ('raiment', '0004_item'), ('raiment', '0005_delete_clothing'), ('raiment', '0006_auto_20191126_1736'), ('raiment', '0007_brand_calendar_calendarday_catalogue_cataloguehas_entry_folder_folderhas_inventory_packlist_user'), ('raiment', '0008_auto_20191210_1854')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('colour', models.CharField(default='red', max_length=32)),
                ('image_link', models.URLField(default='https://assets.pokemon.com/assets/cms2/img/pokedex/full/202.png')),
                ('material', models.CharField(default='Cotton', max_length=32)),
                ('price', models.FloatField(default=399)),
                ('size', models.CharField(default='Medium', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raiment.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wearcount', models.PositiveIntegerField()),
                ('count', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raiment.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('size_letter', models.CharField(max_length=8)),
                ('size_shoe', models.PositiveSmallIntegerField()),
                ('size_pants', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Packlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raiment.Folder')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raiment.Entry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raiment.User')),
            ],
        ),
        migrations.CreateModel(
            name='FolderHas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raiment.Entry')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raiment.Folder')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogueHas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raiment.Catalogue')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raiment.Item')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raiment.Folder')),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raiment.CalendarDay')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raiment.User')),
            ],
        ),
    ]
