# Generated by Django 3.0 on 2020-04-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raiment', '0001_squashed_0008_auto_20191210_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='colour',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='material',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(max_length=8),
        ),
    ]
