# Generated by Django 2.2.5 on 2019-11-05 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raiment', '0002_auto_20191105_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothing',
            old_name='Brand',
            new_name='brand',
        ),
    ]
