# Generated by Django 2.2.5 on 2019-11-26 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raiment', '0004_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clothing',
        ),
    ]
