# Generated by Django 2.2.5 on 2019-11-26 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raiment', '0006_auto_20191126_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raiment.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wearcount', models.PositiveIntegerField()),
                ('count', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raiment.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('size_letter', models.CharField(max_length=8)),
                ('size_shoe', models.PositiveSmallIntegerField()),
                ('size_pants', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Packlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raiment.Folder')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raiment.Entry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raiment.User')),
            ],
        ),
        migrations.CreateModel(
            name='FolderHas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raiment.Entry')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raiment.Folder')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogueHas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raiment.Catalogue')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raiment.Item')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raiment.Folder')),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raiment.CalendarDay')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raiment.User')),
            ],
        ),
    ]
