# Generated by Django 2.2.5 on 2019-12-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raiment', '0007_brand_calendar_calendarday_catalogue_cataloguehas_entry_folder_folderhas_inventory_packlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
